package E_view.loader;

import E_loader.E_Loader;

/**
 *
 * @author mkmacbook
 */
public class E_LoaderWindow extends javax.swing.JFrame {

    private E_Loader loader;

    /** Creates new form LoaderWindow */
    public E_LoaderWindow(E_Loader loader) {
        this.loader = loader;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new E_Background();
        nameTextField = new javax.swing.JTextField();
        joinGameButton = new javax.swing.JButton();
        nicknameLabel = new javax.swing.JLabel();
        hostGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finca");

        background1.setPreferredSize(new java.awt.Dimension(450, 430));

        joinGameButton.setText("Join Game");
        joinGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinGameButtonMouseClicked(evt);
            }
        });

        nicknameLabel.setText("Enter Your Nickname");

        hostGameButton.setText("Host Game");
        hostGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostGameButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(hostGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(joinGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(nicknameLabel)
                .addGap(156, 156, 156))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(nicknameLabel)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//  opens the HostGameWindow.  
    
    private void hostGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostGameButtonMouseClicked
        loader.setNickname(nameTextField.getText());
    	this.setVisible(false);
        loader.openHostGameWindow();
    }//GEN-LAST:event_hostGameButtonMouseClicked

//  opens the JoinGameWindow
    
    private void joinGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinGameButtonMouseClicked
        loader.setNickname(nameTextField.getText());
	this.setVisible(false);
	loader.openJoinGameWindow();
    }//GEN-LAST:event_joinGameButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private E_Background background1;
    private javax.swing.JButton hostGameButton;
    private javax.swing.JButton joinGameButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nicknameLabel;
    // End of variables declaration//GEN-END:variables

}
