package E_view.loader;

import java.rmi.RemoteException;
import java.util.ArrayList;

import E_client.E_FincaClient;

/**
 *
 * @author mkmacbook
 */
public class E_LobbyWindow extends javax.swing.JFrame {

    E_FincaClient myClient;

    /** Creates new form LobbyWindow */
    public E_LobbyWindow(E_FincaClient client) {
        this.myClient = client;
        initComponents();
        if (myClient.isHost()) {
            readyButton.setVisible(false);
            readyLabel.setVisible(false);
            notEverybodyReadyLabel.setVisible(false);
            }
        else {
            startButton.setVisible(false);
            readyLabel.setVisible(false);
            notEverybodyReadyLabel.setVisible(false);
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new E_Background();
        lobbyLabel = new javax.swing.JLabel();
        readyButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        readyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lobbyTextArea = new javax.swing.JTextArea();
        notEverybodyReadyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setPreferredSize(new java.awt.Dimension(430, 450));

        lobbyLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20));
        lobbyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lobbyLabel.setText("Lobby");

        readyButton.setText("Ready");
        readyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readyButtonMouseClicked(evt);
            }
        });

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        readyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        readyLabel.setText("I am ready!");

        lobbyTextArea.setColumns(20);
        lobbyTextArea.setEditable(false);
        lobbyTextArea.setRows(5);
        jScrollPane1.setViewportView(lobbyTextArea);

        notEverybodyReadyLabel.setText("Not everybody ready!");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lobbyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(readyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(readyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notEverybodyReadyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(108, 108, 108))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lobbyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notEverybodyReadyLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//	updates the TextArea of the Lobby with the client's names in it.
    
	public void updateLobby(ArrayList<String> nicknames) {
		lobbyTextArea.setText("");
		for(int i=0; i<nicknames.size(); i++) {
			lobbyTextArea.append(nicknames.get(i) + "\n");
		}
		
	}
	
//	shows the label which shows that not everybody is ready yet.
	
	public void notEverybodyReady() {
            notEverybodyReadyLabel.setVisible(true);
	}

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        	try {
				myClient.initializeGame();
			} catch (RemoteException e) {
				e.printStackTrace();
			}
    }//GEN-LAST:event_startButtonMouseClicked
    
//  sets the state of the client to isReady == true or isReady == false and shows the readyLabel if the player isReady == true.
    
    private void readyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readyButtonMouseClicked
        if (myClient.isReady()) {
            myClient.setReady(false);
            readyLabel.setVisible(false);
            return;
        }
        if (!myClient.isReady()) {
            myClient.setReady(true);
            readyLabel.setVisible(true);
        }
    }//GEN-LAST:event_readyButtonMouseClicked


    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private E_Background background1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lobbyLabel;
    private javax.swing.JTextArea lobbyTextArea;
    private javax.swing.JLabel notEverybodyReadyLabel;
    private javax.swing.JButton readyButton;
    private javax.swing.JLabel readyLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables


}
